<a href="https://colab.research.google.com/github/iamkhan49/Machine-Learning/blob/main/Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Machine Learning**
Machine Learning is a field of AI where machines learn patterns from data and make predictions or decisions without explicitly programmed rules.

**Simple meaning:**

*Instead of manually writing rules…*

*We let machine learn from data*

## Traditional Programming:

Rules + Data → Output

## Machine Learning:

Data + Output → Rules learned by Machine

# Features (X)

Features are input variables given to the machine learning model.

These are the values used by the model to make predictions.

# Label / Target (y)

Label (or Target) is the output variable.

This is what the model tries to predict.

**Remember forever:**

*X → Input / Features*

*y → Output / Label / Target*

# **Model**

A model learns patterns from data and makes predictions.


#**Types of Machine Learning**

Supervised Learning

Unsupervised Learning

Reinforcement Learning

# **Supervised Learning**

Supervised Learning is a machine learning approach where model learns from labeled data. (It Maps)

Labeled data means:

Input already has correct output.

Data has inputs + correct outputs. *(Machine learns relation.)*

Used for:

*  Regression
*  Classification

## **Regression**
Output = continuous numeric value

Regression is a machine learning technique used to predict continuous numerical values.

**Continuous values means numbers like:**

*House Price → 50 lakh*

*Salary → 8 lakh*

*Temperature → 32°C*

These values can be any number in a range.

**Goal of Regression**

The goal is to learn relationship between:

Input (X) → Output (y)

Model learns pattern from data and predicts output.

## **Classification**

Classification is a machine learning technique used to predict categories or classes.

*Output is not a number.*

*Output is a label/category.*

**Examples:**

Spam / Not Spam

Yes / No

Fraud / Not Fraud

Cat / Dog

**Goal of Classification**

The goal is to learn relationship between:

Input (X) → Category Output (y)

Model learns patterns and predicts class.

# **Unsupervised Learning**

Unsupervised Learning is a machine learning approach where model learns from unlabeled data. (It find Patterns)

Unlabeled means:

We only have input data.

No correct output is given.

**Used for:**

**Clustering**

Clustering means grouping similar data points together.

Model automatically creates groups based on similarity.


**Pattern Discovery**

Pattern discovery means finding hidden relationships in data.

Model identifies useful patterns automatically.

# **Reinforcement Learning**

Reinforcement Learning is a machine learning approach where an agent learns by trial and error.

Agent takes actions and gets:

Reward → Good action

Penalty → Bad action

Goal:
*Maximize total reward.*

## **Main Components**

1. **Agent**: The learner / decision maker.

**Example:**

Robot

Game AI

Self-driving car

2. **Environment**: The world where agent acts.

**Example:**

Road

Game

Maze

3. **Action**: What agent does.

**Examples:**

Move left

Move right

Stop

4. **Reward**: Feedback after action.

**Example:**

Correct move → +10

Wrong move → -5

# **Training vs Testing**
Extremely important.

Suppose you have 1000 rows.

You don’t train on all data.

**Split into:**

Training Data → Learn

Testing Data → Evaluate

**Example:**

Train = 80%
Test = 20%

# **Overfitting**

Overfitting happens when a model learns training data too well.

It memorizes training data instead of learning general patterns.

As a result:

Performs very well on training data

Performs poorly on testing/new data

# **Machine Learning Pipeline**

Machine Learning Pipeline is a sequence of steps used to build an ML model.

Each step’s output becomes input for next step.

*Step 1 → Step 2 → Step 3 → Final Output*


**Steps in ML Pipeline**

1) **Data Collection**

Collect data from source.

Examples:

CSV files

Database

APIs

2) **Data Preprocessing**

Clean and prepare data.

Tasks:

Handle missing values

Remove duplicates

Encode categorical data

Feature scaling

3) **Feature Selection / Engineering**

Select important features.

Example:

Area, Rooms → Important

House Color → Less important

4) **Train-Test Split**

Split dataset into:

Training Data

Testing Data

Common split:

80% Train

20% Test

5) **Model Training**

Train ML model using training data.

Examples:

Linear Regression

Decision Tree

KNN

6) **Model Evaluation**

Check model performance.

Common metrics:

Accuracy

Precision

Recall

RMSE

7) **Prediction / Deployment**

Use trained model for real-world prediction.

Example:

House Price Prediction

Spam Detection


# **Visual Idea**

Data Collection

      ↓
Data Preprocessing

      ↓
Feature Engineering

      ↓
Train-Test Split

      ↓
Model Training

      ↓
Model Evaluation

      ↓
Prediction

# **Data Collection**
Data collection is the process of gathering relevant data for solving a problem.

**Simple meaning:**

We collect data that helps machine learn patterns.

**In real companies:**

Average model + excellent data → Great results

Great model + poor data → Poor results

*Data quality often matters more than algorithm choice.*

# **Types of Data**

Two major types.

#**Structured Data**

Organized in rows and columns.

Example:

CSV

Excel

Databases

# **Unstructured Data**

Not organized in table format.

**Examples:**

Images

Videos

Audio

Text

Emails

**Examples in AI:**

Computer Vision

NLP

Speech Recognition

**Traditional ML mostly uses:**

Structured data

**Deep Learning mostly uses:**

Unstructured data

# **Common Data Sources**

* CSV Files

* Excel Files

* Databases

* APIs

* Web Scraping (⚠️ Must follow legal and ethical rules)

* Sensors / IoT Devices

# Public Datasets

Very useful for learning.

Popular sources:

* Kaggle

* UCI ML Repository

* Google Dataset Search

# **Good Data vs Bad Data**

* Good data:

✅ Relevant
✅ Clean
✅ Enough quantity
✅ Accurate

* Bad data:

❌ Missing values
❌ Wrong values
❌ Duplicate rows
❌ Irrelevant features

# **Data collection common problems:**

* Missing Data

* Noisy Data

* Duplicate Data

* Imbalanced Data

# **Data Cleaning**

**Definition**:

Data cleaning means identifying and fixing bad, messy, incomplete, or incorrect data.

**Simple meaning:**

Raw data is messy.

We clean it before training models.

#Real Dataset Practice

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "Age": [25, 30, np.nan, 22, 200, 25],
    "Salary": [50000, np.nan, 60000, 45000, 9999999, 50000],
    "Experience": [2, 4, 3, 1, 100, 2]
}

df = pd.DataFrame(data)
df

     Age     Salary  Experience
0   25.0    50000.0           2
1   30.0        NaN           4
2    NaN    60000.0           3
3   22.0    45000.0           1
4  200.0  9999999.0         100
5   25.0    50000.0           2

# Step 1 — Inspect Dataset

In [5]:
#Never clean blindly, Inspect first.
df.head()    #Used to see first 5 rows of dataset.

     Age     Salary  Experience
0   25.0    50000.0           2
1   30.0        NaN           4
2    NaN    60000.0           3
3   22.0    45000.0           1
4  200.0  9999999.0         100

In [6]:
df.shape      #Used to know dataset dimensions.

(6, 3)

In [7]:
df.info()      #Used to get dataset summary.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Age         5 non-null      float64
 1   Salary      5 non-null      float64
 2   Experience  6 non-null      int64
dtypes: float64(2), int64(1)
memory usage: 276.0 bytes

# Missing Values

In [8]:
df.isnull()    #Check missing values.

     Age  Salary  Experience
0  False   False       False
1  False    True       False
2   True   False       False
3  False   False       False
4  False   False       False
5  False   False       False

In [9]:
df.isnull().sum()   #Count missing values.

Age           1
Salary        1
Experience    0
dtype: int64

#What to do with missing values?

**Common approaches:**

In [10]:
# 1. Remove rows - Removes rows with missing values.
df.dropna()

     Age     Salary  Experience
0   25.0    50000.0           2
3   22.0    45000.0           1
4  200.0  9999999.0         100
5   25.0    50000.0           2

In [11]:
#2. Fill with value - Fill missing with 0.
df.fillna(0)

     Age     Salary  Experience
0   25.0    50000.0           2
1   30.0        0.0           4
2    0.0    60000.0           3
3   22.0    45000.0           1
4  200.0  9999999.0         100
5   25.0    50000.0           2

In [15]:
#3. Fill with mean (Common)
#For Age:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [16]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())

In [17]:
df.isnull().sum()

Age           0
Salary        0
Experience    0
dtype: int64

In [18]:
df

     Age     Salary  Experience
0   25.0    50000.0           2
1   30.0  2040999.8           4
2   60.4    60000.0           3
3   22.0    45000.0           1
4  200.0  9999999.0         100
5   25.0    50000.0           2

**Tips:**

**For numerical columns:**

* mean

* median

**For categorical columns:**

* mode

Common strategy.

# Duplicate Rows

In [19]:
df.duplicated() #Check duplicates.

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [20]:
df.duplicated().sum()  #counts dupicate rows

np.int64(1)

In [ ]:
df = df.drop_duplicates()  #Remove duplicates

In [21]:
df.shape

(6, 3)

#Invalid Values

In [22]:
#Age = 200 is unrealistic.
df["Age"]

0     25.0
1     30.0
2     60.4
3     22.0
4    200.0
5     25.0
Name: Age, dtype: float64

In [23]:
df.describe()

              Age        Salary  Experience
count    6.000000  6.000000e+00    6.000000
mean    60.400000  2.041000e+06   18.666667
std     69.847262  3.979503e+06   39.858082
min     22.000000  4.500000e+04    1.000000
25%     25.000000  5.000000e+04    2.000000
50%     27.500000  5.500000e+04    2.500000
75%     52.800000  1.545750e+06    3.750000
max    200.000000  9.999999e+06  100.000000

In [24]:
#We can filter suspicious rows.

df[df["Age"] > 100]

     Age     Salary  Experience
4  200.0  9999999.0         100

In [30]:
#Remove unrealistic ages.
df = df[df["Age"] <= 100]

In [27]:
df

    Age     Salary  Experience
0  25.0    50000.0           2
1  30.0  2040999.8           4
2  60.4    60000.0           3
3  22.0    45000.0           1
5  25.0    50000.0           2

# Outliers

In [ ]:
#Outlier = value far away from normal range.

#Example:
#Salary = 9999999

#Clearly suspicious.

In [31]:
df["Salary"]

0      50000.0
1    2040999.8
2      60000.0
3      45000.0
5      50000.0
Name: Salary, dtype: float64

In [29]:
df.describe()

             Age        Salary  Experience
count   5.000000  5.000000e+00    5.000000
mean   32.480000  4.492000e+05    2.400000
std    15.869846  8.898598e+05    1.140175
min    22.000000  4.500000e+04    1.000000
25%    25.000000  5.000000e+04    2.000000
50%    25.000000  5.000000e+04    2.000000
75%    30.000000  6.000000e+04    3.000000
max    60.400000  2.041000e+06    4.000000

In [33]:
df = df[df["Salary"] < 1000000]

In [34]:
#Now dataset looks cleaner.
df.describe()

             Age        Salary  Experience
count   4.000000      4.000000    4.000000
mean   33.100000  51250.000000    2.000000
std    18.254862   6291.528696    0.816497
min    22.000000  45000.000000    1.000000
25%    24.250000  48750.000000    1.750000
50%    25.000000  50000.000000    2.000000
75%    33.850000  52500.000000    2.250000
max    60.400000  60000.000000    3.000000

# Cleaning Workflow

1. Inspect data
2. Handle missing values
3. Remove duplicates
4. Fix invalid values
5. Handle outliers
6. Validate cleaned data